"""This module defines constants for ZOE options"""


class ZOEOPTION:
    """String constants for ZOE options"""
    OPTIONS = "Options"
    GAME_TITLE = "Zoe"
    GAME_TITLE_FULL = "Zone of the Enders"
    VERSION = "Version"
    VERSION_NUMBER = "PLSGIVEVERSIONNUMBER-dev"  # This is automatically updated by the GitHub actions workflow
    START_INVENTORY_FROM_POOL = "Start Inventory From Pool"
    ENEMY_COUNTER = "Enemy Counter"
    LOCAL_SERVERS = "Local Servers"
    MODULES = "Modules"
    WEAPONS = "Weapons"
    DEATHLINK = "Death Link"
    EXCLUDE = "Zoe Exclude Locations"
    TOTAL_LOCATIONS = "Total Locations"
    PROCESSED_LOCATIONS = "Processed Locations"
    INFOS = "Infos"
    PASSCODES_ITEMS = "Passcodes Items"
    PASSCODES_LOCS = "Passcodes Locations"
    VRTRAINING = "VR Training"
    LINEAR_PLAY = "Linear Progression"
    FILLER_WEIGHT = "Filler Weight"
    ENABLE_TRAPS = "Enable Traps"
    TRAP_WEIGHT = "Trap Weight"
    CONFIGURATION = "Configuration"