"""This module contains string constants for each general game location"""


class ZOELOCATION:
    """String constants for locations"""
    HANGAR_1_FIRST_RAPTOR = "Hangar.1: First Raptor destroyed"
    HANGAR_1_METATRON_ORE = "Hangar.1: Heal yourself with the Metatron Ore"
    FACTORY_1_TWO_RAPTORS = "Factory.1: Destroy the two Raptors"
    FACTORY_1_TWO_MUMMYHEADS = "Factory.1: Destroy the two Mummyheads"
    FACTORY_1_NEITH = "Factory.1: Drive off Neith"
    FACTORY_1_SCOUTING_MODULE_LOCAL_SERVER = "Factory.1: Use the Scouting Module Local Server"
    FACTORY_1_GLOBAL_PASSCODE = "Factory.1: Obtain the Global Passcode"
    FACTORY_1_FLIGHT_MODULE_LOCAL_SERVER = "Factory.1: Use the Flight Module Local Server"
    FACTORY_1_FLY_AWAY = "Factory.1: Fly Away"
    TOWN_1_TEMPEST = "Town.1: Destroy Tempest"
    TOWN_1_JAVELIN_PASSCODE = "Town.1: Obtain the Javelin Passcode"
    TOWN_1_JAVELIN = "Town.1: Use the Javelin Local Server"
    TOWN_1_JAVELIN_AMMO = "Town.1: Obtain Javelin ammo"
    TOWN_2_JAVELIN_AMMO = "Town.2: Obtain Javelin ammo"
    TOWN_2_PHALANX_PASSCODE = "Town.1: Obtain the Phalanx Passcode"
    TOWN_2_PHALANX = "Town.2: Use the Phalanx Local Server"
    TOWN_2_RESCUE_MISSION = "Town.2: Rescue the survivors"
    TOWN_2_RESCUE_RANK_A = "Town.2: Complete the Rescue with a A rank"
    TOWN_2_RESCUE_RANK_B = "Town.2: Complete the Rescue with a B rank"
    TOWN_2_RESCUE_RANK_C = "Town.2: Complete the Rescue with a C rank"
    TOWN_2_RESCUE_RANK_D = "Town.2: Complete the Rescue with a D rank"
    TOWN_2_RESCUE_RANK_E = "Town.2: Complete the Rescue with a E rank"
    FACTORY_1_ANTILIA_PASSCODE = "Factory.1: Obtain the Antilia Passcode"
    FACTORY_1_ANTILIA_INFO = "Factory.1: Use the Antilia Info Local Server"
    ANTILIA_INFO = "Learn about the EPS Antennas"
    TOWN_1_RESCUE_MISSION = "Town.1: Save the church"
    TOWN_1_RESCUE_RANK_A = "Town.1: Complete the Rescue with a A rank"
    TOWN_1_RESCUE_RANK_B = "Town.1: Complete the Rescue with a B rank"
    TOWN_1_RESCUE_RANK_C = "Town.1: Complete the Rescue with a C rank"
    TOWN_1_RESCUE_RANK_D = "Town.1: Complete the Rescue with a D rank"
    TOWN_1_RESCUE_RANK_E = "Town.1: Complete the Rescue with a E rank"
    TOWN_1_JAVELIN_AMMO_2 = "Town.1: Obtain Javelin ammo (2)"
    TOWN_1_PHALANX_AMMO = "Town.1: Obtain Phalanx ammo"
    CITY_1_PHALANX_AMMO = "City.1: Obtain Phalanx ammo"
    CITY_1_PHALANX_AMMO_2 = "City.1: Obtain Phalanx ammo (2)"
    CITY_1_GEYSER_PASSCODE = "City.1: Obtain the Geyser Passcode"
    CITY_1_GEYSER = "City.1: Use the Geyser Local Server"
    TOWN_2_JAVELIN_AMMO_2 = "Town.2: Obtain Javelin ammo (2)"
    TOWN_2_PHALANX_AMMO = "Town.2: Obtain Phalanx ammo"
    TOWN_2_SNIPER = "Town.2: Destroy the porters and retrieve the Sniper"
    CITY_1_DESTROY_RELAY_BLOCK = "City.1: Push the forcefield backwards"
    UNLOCK_EPS = "Gain access to the EPS Antennas"
