"""This module contains string constants used for tagging each location type"""


class ZOETAG:
    """String constants for each location tag"""
    ENEMY = "Enemy"
    ENEMYCOUNT = "Enemy Count"
    HARD_ENEMY = "Hard Enemy"
    UNSTABLE = "Unstable"
    MISSIONS = "Missions"
    WEAPONS = "Weapons"
    LOCAL_SERVERS = "Local Servers"
    PASSCODES = "Passcodes"
    VR = "VR"
    VISIT = "Visits"
    SQUADS_ENGAGED = "Squads Engaged"
    NOT_IMPLEMENTED = "Not Implemented"
    LEVEL = "Level"
    AMMO = "Ammo" 
    RESCUE = "Rescue" 