"""This module contains string constants for the visiting area locations"""


class ZOEVISIT:
    """String constants for the visit locations"""
    HANGAR_1_VISIT = "Hangar.1: Visit: Welcome to the Zone of the Enders"
    FACTORY_1_VISIT = "Factory.1: Visit"
    TOWN_1_VISIT = "Town.1: Visit"
    TOWN_2_VISIT = "Town.2: Visit"
    CITY_1_VISIT = "City.1: Visit"
    EPS_1_VIST = "EPS.1: Visit"
    EPS_2_VIST = "EPS.2: Visit"
    TOWN_3_VISIT = "Town.3: Visit"
    PARK_1_VISIT = "Park.1: Freefall"
    CITY_2_VISIT = "City.2: Visit"
    FACTORY_2_VISIT = "Factory.2: Visit"
    MOUNTAIN_1_VISIT = "Mountain.1: Visit"
    WAREHOUSE_1_VISIT = "Warehouse.1: Visit"
    TUNNEL_1_VISIT = "Tunnel.1: Passing by"
    HUB_1_VISIT = "Hub.1: End of the Line"
